SEED: 11

# --- environment ---
MAP_SIZE: [15, 15]
MAX_EPISODE_TICKS: 10000

# --- population ---
N_TEAMS: 2
POP_SIZE: 500             # 500 genomes choosen a random
MAX_TEAM_SIZE: 25         # in order to limit fork
TEAM_EPISODE_SIZE: 10     # Number of genome which will play each gen
REINJECT_FRAC: 0.1

# --- network ---
# state_dim computed at runtime
HIDDEN_LAYERS: [128, 64]

# --- evolution ---
N_GENERATIONS: 5000
ELITE_FRAC: 0.1           # keep top 10%
MUTATION_STD: 0.05
FORK_MUTATION_STD: 0.01

# --- training control ---
WIN_STREAK_STOP: 50       # stop if one team wins 50 consecutive episodes
CHECKPOINT_INTERVAL: 100  # save best genome every 100 generations